### ISSUE TITLE
SFS from demes does not scale as expected.

### ISSUE THREAD

**Issue by sgravel** [MomentsLD/moments#153]
Goal: obtain the SFS from a model fit with the Poisson likelihood. "Output" is the poisson-fit demes object 

Attempted solution:  
fs = moments.Spectrum.from_demes(output, samples={"MSL": data.sample_sizes})
moments.Plotting.plot_1d_comp_Poisson(L*mu* fs, data)

This produces an un-scaled fs. 
![](https://github.com/MomentsLD/moments/assets/63737044/752a2c9f-0dfc-4ff9-a150-53ba11c78d5c).

To get the correctly scaled version, we have to multiply this by the ancestral Ne. 

moments.Plotting.plot_1d_comp_Poisson(Ne*L*mu* fs, data) to fit properly . 

It seems like 
fs = moments.Spectrum.from_demes(output, samples={"MSL": data.sample_sizes}) producing an unscaled version even with Ne=None.

**Comment by apragsdale** [comment]
Yes, currently the functionality only returns a "default"-scaled SFS with theta=1. Under the hood, there is some infrastructure to be able to add arguments for mutation rate, sequence length, etc, to get a properly scaled SFS, but I didn't get around to adding these yet. Additionally, allowing for a reversible mutation model could be included. It just requires adding the keyword arguments and putting together some tests.

What would you think would be a good API and arguments for this? And what would you think would be good default behavior?

If `u` or `Lu` is provided, then I would think you'd want `theta=4*Ne*Lu`, where `Ne` is taken from the graph or provided as an argument. If the mutation rate isn't provided, should it default to 1, so that the SFS is scaled by `4*Ne`, and could later be just multiplied by `Lu`?

**Comment by apragsdale** [comment]
I also think `Ne` should be taken directly from the demes graph, as the initial size of the root population. Otherwise, setting `Ne` manually results in mis-scaled sizes when integrating. I should clean up these design choices.

**Comment by sgravel** [comment]
Yes, in terms of UI, I think that the default should by u = L = 1, but the Ne should be read from the demes. Maybe it would be worth having a print statement of Ne, u, L, because even in the best case this can be confusing... 

I am not sure why setting Ne manually results in mis-scaling. Do you mean setting it as an argument to this function? That would be a problem. I suppose that it may be more helpful to have a "scaling" argument, that scales all sizes and times appropriately, and then returns the correctly-scaled model? (or do we have that already)

**Comment by apragsdale** [comment]
I think that all makes sense. At some point, I had decided to allow Ne to be passed separately, to have more flexibility with scaling mutation rates, selection coefficientents, etc. But I think it's just confusing and results in mismatches between the solution at steady state and subsequent size changes or integration times. It could be all handled consistently, but I think it just over-complicates things. I'd suggest we remove the Ne optional keyword argument.

We don't have a function that rescales the demes model by some factor. I agree that would be a really useful tool (and not just for moments). I think it would be easy to do. I'll open a separate issue and implement it in a subsequent PR.
